### ISSUE TITLE
No such file or directory (os error 2)

### ISSUE THREAD

**Issue by goncalopolido** [hizkifw/tempbin#1]
error occurs after uploading file.

![image](https://github.com/hizkifw/tempbin/assets/83615960/480ca74c-d5a5-4de6-bd97-bedecc4b919d)

![image](https://github.com/hizkifw/tempbin/assets/83615960/a85719c5-f9f4-4c41-bb7f-a1876276382c)

**Comment by hizkifw** [comment]
Hi, please create a folder named `uploads` in the working directory.

**Comment by hizkifw** [comment]
I've fixed this in the latest commit, the `uploads` folder will be created on startup.
